// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingGarageApi.Data;

#nullable disable

namespace ParkingGarageApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250207155609_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ParkingGarageApi.Models.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SpotNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ParkingSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SpotNumber = 1,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 2,
                            SpotNumber = 2,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 3,
                            SpotNumber = 3,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 4,
                            SpotNumber = 4,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 5,
                            SpotNumber = 5,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 6,
                            SpotNumber = 6,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 7,
                            SpotNumber = 7,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 8,
                            SpotNumber = 8,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 9,
                            SpotNumber = 9,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 10,
                            SpotNumber = 10,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 11,
                            SpotNumber = 11,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 12,
                            SpotNumber = 12,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 13,
                            SpotNumber = 13,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 14,
                            SpotNumber = 14,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 15,
                            SpotNumber = 15,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 16,
                            SpotNumber = 16,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 17,
                            SpotNumber = 17,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 18,
                            SpotNumber = 18,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 19,
                            SpotNumber = 19,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 20,
                            SpotNumber = 20,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 21,
                            SpotNumber = 21,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 22,
                            SpotNumber = 22,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 23,
                            SpotNumber = 23,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 24,
                            SpotNumber = 24,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 25,
                            SpotNumber = 25,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 26,
                            SpotNumber = 26,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 27,
                            SpotNumber = 27,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 28,
                            SpotNumber = 28,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 29,
                            SpotNumber = 29,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 30,
                            SpotNumber = 30,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 31,
                            SpotNumber = 31,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 32,
                            SpotNumber = 32,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 33,
                            SpotNumber = 33,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 34,
                            SpotNumber = 34,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 35,
                            SpotNumber = 35,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 36,
                            SpotNumber = 36,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 37,
                            SpotNumber = 37,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 38,
                            SpotNumber = 38,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 39,
                            SpotNumber = 39,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 40,
                            SpotNumber = 40,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 41,
                            SpotNumber = 41,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 42,
                            SpotNumber = 42,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 43,
                            SpotNumber = 43,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 44,
                            SpotNumber = 44,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 45,
                            SpotNumber = 45,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 46,
                            SpotNumber = 46,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 47,
                            SpotNumber = 47,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 48,
                            SpotNumber = 48,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 49,
                            SpotNumber = 49,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 50,
                            SpotNumber = 50,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 51,
                            SpotNumber = 51,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 52,
                            SpotNumber = 52,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 53,
                            SpotNumber = 53,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 54,
                            SpotNumber = 54,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 55,
                            SpotNumber = 55,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 56,
                            SpotNumber = 56,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 57,
                            SpotNumber = 57,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 58,
                            SpotNumber = 58,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 59,
                            SpotNumber = 59,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 60,
                            SpotNumber = 60,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 61,
                            SpotNumber = 61,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 62,
                            SpotNumber = 62,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 63,
                            SpotNumber = 63,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 64,
                            SpotNumber = 64,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 65,
                            SpotNumber = 65,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 66,
                            SpotNumber = 66,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 67,
                            SpotNumber = 67,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 68,
                            SpotNumber = 68,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 69,
                            SpotNumber = 69,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 70,
                            SpotNumber = 70,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 71,
                            SpotNumber = 71,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 72,
                            SpotNumber = 72,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 73,
                            SpotNumber = 73,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 74,
                            SpotNumber = 74,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 75,
                            SpotNumber = 75,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 76,
                            SpotNumber = 76,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 77,
                            SpotNumber = 77,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 78,
                            SpotNumber = 78,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 79,
                            SpotNumber = 79,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 80,
                            SpotNumber = 80,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 81,
                            SpotNumber = 81,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 82,
                            SpotNumber = 82,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 83,
                            SpotNumber = 83,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 84,
                            SpotNumber = 84,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 85,
                            SpotNumber = 85,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 86,
                            SpotNumber = 86,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 87,
                            SpotNumber = 87,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 88,
                            SpotNumber = 88,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 89,
                            SpotNumber = 89,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 90,
                            SpotNumber = 90,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 91,
                            SpotNumber = 91,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 92,
                            SpotNumber = 92,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 93,
                            SpotNumber = 93,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 94,
                            SpotNumber = 94,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 95,
                            SpotNumber = 95,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 96,
                            SpotNumber = 96,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 97,
                            SpotNumber = 97,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 98,
                            SpotNumber = 98,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 99,
                            SpotNumber = 99,
                            Status = "Szabad"
                        },
                        new
                        {
                            Id = 100,
                            SpotNumber = 100,
                            Status = "Szabad"
                        });
                });

            modelBuilder.Entity("ParkingGarageApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
